
import { PortfolioData } from './types';

export const THEME_OPTIONS = [
  { id: 'neon', name: 'Cyber Azure', color: '#0ea5e9' },
  { id: 'gold', name: 'Luxury Gold', color: '#d4af37' },
  { id: 'rose', name: 'Deep Crimson', color: '#e11d48' },
  { id: 'emerald', name: 'Nordic Forest', color: '#10b981' }
];

export const LAYOUT_OPTIONS = [
  { id: 'default', name: 'Standard Flow' },
  { id: 'minimal', name: 'Clean Minimal' },
  { id: 'brutalist', name: 'Neo Brutalist' },
  { id: 'split', name: 'Split Screen' },
  { id: 'classic', name: 'Classic' }
];

export const CURRENCY_SYMBOLS = [
  { label: 'BDT (৳)', value: '৳' },
  { label: 'USD ($)', value: '$' },
  { label: 'EUR (€)', value: '€' },
  { label: 'GBP (£)', value: '£' }
];

export const INITIAL_DATA: PortfolioData = {
  name: "MD Ahbab Khan",
  nameBn: "এমডি আহবাব খান",
  logoUrl: "",
  title: "Professional Web Developer & Creative Designer",
  titleBn: "পেশাদার ওয়েব ডেভেলপার এবং ক্রিয়েটিভ ডিজাইনার",
  bio: "Hello, I am MD Ahbab Khan. I am a passionate Data Analyst who enjoys turning raw data into meaningful insights. I work with data to discover patterns, solve problems, and help businesses make smarter decisions. With a strong interest in analytics, visualization, and data-driven strategies, I focus on transforming complex information into clear and actionable results that create real value for organizations and individuals.",
  bioBn: "হ্যালো, আমি এমডি আহবাব খান। আমি একজন নিবেদিত ডাটা অ্যানালিস্ট যিনি কাঁচা ডাটাকে অর্থপূর্ণ অন্তর্দৃষ্টিতে রূপান্তর করতে পছন্দ করেন। আমি প্যাটার্ন আবিষ্কার করতে, সমস্যা সমাধান করতে এবং ব্যবসায়িকদের স্মার্ট সিদ্ধান্ত নিতে সাহায্য করার জন্য ডাটা নিয়ে কাজ করি। অ্যানালিটিক্স, ভিজ্যুয়ালাইজেশন এবং ডাটা-চালিত কৌশলের প্রতি গভীর আগ্রহের সাথে, আমি জটিল তথ্যকে পরিষ্কার এবং কার্যকর ফলাফলে রূপান্তর করার দিকে মনোনিবেশ করি যা সংস্থা এবং ব্যক্তিদের জন্য প্রকৃত মূল্য তৈরি করে।",
  currentWork: "Freelance Full Stack Developer",
  currentWorkBn: "ফ্রিল্যান্স ফুল স্ট্যাক ডেভেলপার",
  profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1000&auto=format&fit=crop", 
  aboutText: "I am MD Ahbab Khan, a tech enthusiast and developer with a focus on crafting high-quality web applications. With expertise in modern frameworks and a keen eye for design, I strive to create web experiences that are not only functional but also visually stunning. My goal is to help clients transform their ideas into reality through clean, efficient code.",
  aboutTextBn: "আমি এমডি আহবাব খান, একজন প্রযুক্তিপ্রেমী এবং ডেভেলপার যার লক্ষ্য উচ্চমানের ওয়েব অ্যাপ্লিকেশন তৈরি করা। আধুনিক ফ্রেমওয়ার্ক এবং ডিজাইনের প্রতি তীক্ষ্ণ দৃষ্টির সাথে, আমি এমন ওয়েব অভিজ্ঞতা তৈরি করার চেষ্টা করি যা কেবল কার্যকরী নয় বরং দৃশ্যত অত্যাশ্চর্য। আমার লক্ষ্য হলো ক্লায়েন্টদের তাদের আইডিয়াগুলোকে পরিষ্কার এবং দক্ষ কোডের মাধ্যমে বাস্তবে রূপান্তর করতে সাহায্য করা।",
  email: "khantaousi@gmail.com",
  phone: "01518934191",
  theme: 'neon',
  layout: 'default',
  showAbout: true,
  showSkills: true,
  showBlog: true,
  showGallery: true,
  showContact: true,
  showClock: true,
  showNotice: true,
  showWork: true,
  showJobExperience: true,
  showEventSection: true,
  showSkillsChart: true,
  whatsappNumber: "+8801518934191",
  notice: {
    text: "স্বাগতম! আমি MD Ahbab Khan। আমার অফিসিয়াল পোর্টফোলিওতে আপনাকে স্বাগতম। যেকোনো সেবার জন্য যোগাযোগ করুন।",
    updatedAt: new Date().toISOString(),
    speed: 45
  },
  event: {
    title: "EID MUBARAK",
    titleBn: "ঈদ মোবারক",
    subtitle: "Wishing you and your family a blessed Ramadan and a joyous Eid filled with peace, prosperity, and happiness.",
    subtitleBn: "আপনার এবং আপনার পরিবারের জন্য একটি বরকতময় রমজান এবং শান্তি, সমৃদ্ধি ও সুখে ভরপুর একটি আনন্দময় ঈদের শুভেচ্ছা রইল।",
    animationType: "float",
    theme: "islamic"
  },
  seo: {
    metaTitle: "MD Ahbab Khan | Professional Web Developer",
    metaTitleBn: "এমডি আহবাব খান | পেশাদার ওয়েব ডেভেলপার",
    metaDescription: "Official portfolio of MD Ahbab Khan, a professional web developer and creative designer specializing in modern web applications.",
    metaDescriptionBn: "এমডি আহবাব খান-এর অফিসিয়াল পোর্টফোলিও, একজন পেশাদার ওয়েব ডেভেলপার এবং ক্রিয়েটিভ ডিজাইনার যিনি আধুনিক ওয়েব অ্যাপ্লিকেশন তৈরিতে বিশেষজ্ঞ।",
    metaKeywords: "MD Ahbab Khan, Web Developer, Portfolio, React Developer, Full Stack Developer",
    favicon: "https://picsum.photos/seed/favicon/32/32"
  },
  socialLinks: [
    { id: "1", platform: "GitHub", url: "https://github.com" },
    { id: "2", platform: "LinkedIn", url: "https://linkedin.com" },
    { id: "3", platform: "Facebook", url: "https://facebook.com" }
  ],
  projects: [
    {
      id: "1",
      title: "Pohela Boishakh: The Bengali New Year",
      titleBn: "পহেলা বৈশাখ: বাংলা নববর্ষ",
      description: "A vibrant celebration of the Bengali New Year, marked by colorful processions (Mangal Shobhajatra), traditional music, and festive foods like Panta Ilish.",
      descriptionBn: "বাংলা নববর্ষের একটি প্রাণবন্ত উদযাপন, যা রঙিন শোভাযাত্রা (মঙ্গল শোভাযাত্রা), ঐতিহ্যবাহী সঙ্গীত এবং পান্তা ইলিশের মতো উৎসবমুখর খাবারের মাধ্যমে পালিত হয়।",
      image: "https://picsum.photos/seed/boishakh/600/400",
      link: "#"
    },
    {
      id: "2",
      title: "The Art of Rickshaw Painting",
      titleBn: "রিকশা পেইন্টিংয়ের শিল্প",
      description: "Rickshaw art is a unique and colorful folk art of Bangladesh, featuring intricate motifs, film stars, and rural landscapes painted on cycle rickshaws.",
      descriptionBn: "রিকশা শিল্প বাংলাদেশের একটি অনন্য এবং রঙিন লোকশিল্প, যাতে সাইকেল রিকশায় আঁকা জটিল মোটিফ, চলচ্চিত্র তারকা এবং গ্রামীণ দৃশ্য ফুটে ওঠে।",
      image: "https://picsum.photos/seed/rickshaw/600/400",
      link: "#"
    },
    {
      id: "3",
      title: "Jamdani: The Woven Heritage",
      titleBn: "জামদানি: বোনা ঐতিহ্য",
      description: "Jamdani is a fine muslin textile woven by hand, recognized as an Intangible Cultural Heritage of Humanity by UNESCO, representing centuries of Bengali craftsmanship.",
      descriptionBn: "জামদানি হলো হাতে বোনা একটি সূক্ষ্ম মসলিন টেক্সটাইল, যা ইউনেস্কো কর্তৃক মানবতার অমূর্ত সাংস্কৃতিক ঐতিহ্য হিসেবে স্বীকৃত এবং এটি শতাব্দী প্রাচীন বাঙালি কারুশিল্পের প্রতিনিধিত্ব করে।",
      image: "https://picsum.photos/seed/jamdani/600/400",
      link: "#"
    }
  ],
  gallery: [
    { id: "1", image: "https://picsum.photos/800/800?random=10", title: "Tech Innovation", titleBn: "প্রযুক্তিগত উদ্ভাবন" },
    { id: "2", image: "https://picsum.photos/800/800?random=11", title: "Creative Workspace", titleBn: "সৃজনশীল কর্মক্ষেত্র" }
  ],
  skills: [
    { id: "1", name: "HTML & CSS", nameBn: "এইচটিএমএল এবং সিএসএস" },
    { id: "2", name: "JavaScript", nameBn: "জাভাস্ক্রিপ্ট" },
    { id: "3", name: "React JS", nameBn: "রিয়্যাক্ট জেএস" },
    { id: "4", name: "Tailwind CSS", nameBn: "টেইলউইন্ড সিএসএস" },
    { id: "5", name: "Node.js", nameBn: "নোড জেএস" }
  ],
  jobExperiences: [
    { 
      id: "1", 
      companyName: "Tech Corp", 
      website: "https://techcorp.com", 
      logoUrl: "https://picsum.photos/100/100?random=50", 
      duration: "2 years", 
      durationBn: "২ বছর",
      description: "Full Stack Developer",
      descriptionBn: "ফুল স্ট্যাক ডেভেলপার"
    }
  ]
};

export const TRANSLATIONS = {
  en: {
    navHome: "Home",
    navAbout: "About",
    navBlog: "Blog",
    navGallery: "Gallery",
    navContact: "Contact",
    navAdmin: "Admin",
    heroWelcome: "Welcome to my digital profile",
    heroIam: "I am",
    heroEmailBtn: "Send Email",
    heroStatus: "Available Now",
    heroWorkLabel: "Currently working at",
    clockLabel: "Bangladesh Time",
    skillsHeader: "Skills",
    aboutHeader: "About Me",
    blogHeader: "My Blog",
    galleryHeader: "Photo Gallery",
    productsHeader: "My Products",
    orderBtn: "Order Now",
    orderModalTitle: "Order Placement",
    orderNameLabel: "Full Name",
    orderContactLabel: "Phone Number",
    orderCountryLabel: "Country",
    orderConfirmBtn: "Confirm Order",
    orderSuccess: "Thank you for placing your order. MD Ahbab Khan will contact you soon.",
    blogReadMore: "Read More",
    blogDesc: "Insights into my process and discoveries.",
    galleryDesc: "Visual snapshots of my creative journey.",
    contactHeader: "Get in Touch",
    contactSub: "Ready to start a new project? Let's talk.",
    contactEmailLabel: "Email Me",
    contactPhoneLabel: "Call Me",
    contactSocialLabel: "Social Networks",
    footerAdmin: "Admin Dashboard",
    loginHeader: "Security Access",
    loginIdLabel: "System ID",
    loginPassLabel: "Access Token",
    loginBtn: "Authorize",
    loginBack: "Exit to Portal",
    loginWelcome: "Welcome Admin",
    loginProceed: "Continue to Login",
    adminHeader: "System Core",
    adminSub: "Portfolio Management",
    adminMenu: "Control Center",
    adminBasic: "Core Identity",
    adminSkills: "Expertise",
    adminBlog: "Editorial",
    adminGallery: "Media Assets",
    adminNotice: "Global Broadcast",
    adminContact: "Contact Settings",
    adminJobExperience: "Job Experience",
    adminEvent: "Event Banner",
    adminSEO: "SEO Settings",
    adminDeploy: "Cloud Core",
    adminSave: "Sync Changes",
    adminSaving: "Syncing...",
    adminSaved: "Live!",
    adminLogout: "Disconnect",
    adminViewSite: "Public View",
    adminNewSkill: "Add Competency",
    adminNewPost: "Draft Story",
    adminNewPhoto: "Upload Media",
    adminNewLink: "Signal Link",
    adminNewJob: "Add Job",
    adminTheme: "Visual Environment",
    adminVisibility: "Module Toggle",
    adminWorkplace: "Station",
    syncLoading: "Loading Profile...",
    visLabelAbout: "About Section",
    visLabelSkills: "Skills Section",
    visLabelBlog: "Blog Section",
    visLabelGallery: "Gallery Section",
    visLabelContact: "Contact Section",
    visLabelClock: "Live Clock",
    visLabelNotice: "Notice Board",
    visLabelWork: "Work Status",
    visLabelJobExperience: "Job Experience Section",
    visLabelEvent: "Event Banner",
    fileTransfer: "File Transfer",
    noticeLabel: "ALERT",
    noticePublished: "Broadcasted",
    showLess: "Show Less",
    readMore: "Read More"
  },
  bn: {
    navHome: "হোম",
    navAbout: "পরিচয়",
    navBlog: "ব্লগ",
    navGallery: "গ্যালারি",
    navContact: "যোগাযোগ",
    navAdmin: "অ্যাডমিন",
    heroWelcome: "আমার ডিজিটাল প্রোফাইলে স্বাগতম",
    heroIam: "আমি",
    heroEmailBtn: "ইমেইল পাঠান",
    heroStatus: "অ্যাভেইলবল",
    heroWorkLabel: "বর্তমান কর্মস্থল",
    clockLabel: "বাংলাদেশ সময়",
    skillsHeader: "দক্ষতাসমূহ",
    aboutHeader: "আমার সম্পর্কে",
    blogHeader: "ব্লগ",
    galleryHeader: "গ্যালারি",
    productsHeader: "পণ্যসমূহ",
    orderBtn: "অর্ডার করুন",
    orderModalTitle: "অর্ডার ফর্ম",
    orderNameLabel: "আপনার নাম",
    orderContactLabel: "ফোন নম্বর",
    orderCountryLabel: "দেশ",
    orderConfirmBtn: "অর্ডার সম্পন্ন করুন",
    orderSuccess: "অর্ডারটি সফলভাবে সম্পন্ন হয়েছে। শীঘ্রই আপনার সাথে যোগাযোগ করা হবে।",
    blogReadMore: "বিস্তারিত",
    blogDesc: "প্রযুক্তি এবং জীবনধারা নিয়ে আমার ভাবনা।",
    galleryDesc: "স্মৃতি এবং কাজের কিছু মুহূর্ত।",
    contactHeader: "যোগাযোগ করুন",
    contactSub: "আপনার কোনো আইডিয়া থাকলে সরাসরি কথা বলতে পারি।",
    contactEmailLabel: "ইমেইল করুন",
    contactPhoneLabel: "সরাসরি কল",
    contactSocialLabel: "সোশ্যাল মিডিয়া",
    footerAdmin: "ড্যাশবোর্ড",
    loginHeader: "সুরক্ষিত প্রবেশ",
    loginIdLabel: "ইউজার আইডি",
    loginPassLabel: "পাসওয়ার্ড",
    loginBtn: "লগইন",
    loginBack: "হোমে ফিরুন",
    loginWelcome: "স্বাগতম অ্যাডমিন",
    loginProceed: "লগইন করতে এগিয়ে যান",
    adminHeader: "সিস্টেম কন্ট্রোল",
    adminSub: "ম্যানেজমেন্ট ড্যাশবোর্ড",
    adminMenu: "কন্টেন্ট মেনু",
    adminBasic: "মৌলিক তথ্য",
    adminSkills: "দক্ষতাসমূহ",
    adminBlog: "ব্লগ ম্যানেজমেন্ট",
    adminGallery: "মিডিয়া ফাইল",
    adminNotice: "ব্রডকাস্ট",
    adminContact: "যোগাযোগ সেটিংস",
    adminJobExperience: "কাজের অভিজ্ঞতা",
    adminEvent: "ইভেন্ট ব্যানার",
    adminSEO: "এসইও সেটিংস",
    adminSave: "লাইভ আপডেট",
    adminSaving: "Syncing...",
    adminSaved: "লাইভ!",
    adminLogout: "লগ আউট",
    adminViewSite: "ওয়েবসাইট ভিউ",
    adminNewSkill: "নতুন স্কিল",
    adminNewPost: "নতুন পোস্ট",
    adminNewPhoto: "ছবি যোগ করুন",
    adminNewLink: "নতুন লিংক",
    adminNewJob: "নতুন চাকরি",
    adminTheme: "ওয়েবসাইট থিম",
    adminVisibility: "সেকশন কন্ট্রোল",
    adminWorkplace: "কর্মস্থল",
    syncLoading: "ডাটা লোড হচ্ছে...",
    visLabelAbout: "সম্পর্কে সেকশন",
    visLabelSkills: "দক্ষতা সেকশন",
    visLabelBlog: "ব্লগ সেকশন",
    visLabelGallery: "গ্যালারি সেকশন",
    visLabelContact: "যোগাযোগ সেকশন",
    visLabelClock: "লাইভ ঘড়ি",
    visLabelNotice: "নোটিশ বোর্ড",
    visLabelWork: "কাজের স্ট্যাটাস",
    visLabelJobExperience: "কাজের অভিজ্ঞতা সেকশন",
    visLabelEvent: "ইভেন্ট ব্যানার",
    fileTransfer: "ফাইল ট্রান্সফার",
    noticeLabel: "জরুরী নোটিশ",
    noticePublished: "প্রকাশিত",
    showLess: "সংক্ষেপ করুন",
    readMore: "বিস্তারিত পড়ুন"
  }
};
