
import { PortfolioData } from './types';

export const THEME_OPTIONS = [
  { id: 'neon', name: 'Cyber Azure', color: '#0ea5e9' },
  { id: 'gold', name: 'Luxury Gold', color: '#d4af37' },
  { id: 'rose', name: 'Deep Crimson', color: '#e11d48' },
  { id: 'emerald', name: 'Nordic Forest', color: '#10b981' }
];

export const INITIAL_DATA: PortfolioData = {
  name: "MD Ahbab Khan",
  title: "Professional Web Developer & Creative Designer",
  bio: "Hello, I am MD Ahbab Khan. I am a passionate web developer dedicated to building modern, responsive, and user-centric digital solutions that empower businesses and individuals.",
  currentWork: "Freelance Full Stack Developer",
  profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1000&auto=format&fit=crop", 
  aboutText: "I am MD Ahbab Khan, a tech enthusiast and developer with a focus on crafting high-quality web applications. With expertise in modern frameworks and a keen eye for design, I strive to create web experiences that are not only functional but also visually stunning. My goal is to help clients transform their ideas into reality through clean, efficient code.",
  email: "khantaousi@gmail.com",
  phone: "01518934191",
  theme: 'neon',
  showAbout: true,
  showSkills: true,
  showBlog: true,
  showGallery: true,
  showContact: true,
  showClock: true,
  showNotice: true,
  showWork: true,
  notice: {
    text: "স্বাগতম! আমি MD Ahbab Khan। আমার অফিসিয়াল পোর্টফোলিওতে আপনাকে স্বাগতম। যেকোনো সেবার জন্য যোগাযোগ করুন।",
    updatedAt: new Date().toISOString()
  },
  socialLinks: [
    { id: "1", platform: "GitHub", url: "https://github.com" },
    { id: "2", platform: "LinkedIn", url: "https://linkedin.com" },
    { id: "3", platform: "Facebook", url: "https://facebook.com" }
  ],
  projects: [
    {
      id: "1",
      title: "Portfolio CMS Development",
      description: "A professional management system for personal portfolios with cloud storage integration.",
      image: "https://picsum.photos/600/400?random=1",
      link: "#"
    }
  ],
  gallery: [
    { id: "1", image: "https://picsum.photos/800/800?random=10", title: "Tech Innovation" },
    { id: "2", image: "https://picsum.photos/800/800?random=11", title: "Creative Workspace" }
  ],
  skills: [
    { id: "1", name: "HTML & CSS" },
    { id: "2", name: "JavaScript" },
    { id: "3", name: "React JS" },
    { id: "4", name: "Tailwind CSS" },
    { id: "5", name: "Node.js" }
  ]
};

export const TRANSLATIONS = {
  en: {
    navAbout: "About",
    navBlog: "Blog",
    navGallery: "Gallery",
    navContact: "Contact",
    navAdmin: "Admin",
    heroWelcome: "Welcome to my digital profile",
    heroIam: "I am",
    heroEmailBtn: "Send Email",
    heroStatus: "Available Now",
    heroWorkLabel: "Currently working at",
    clockLabel: "Bangladesh Time",
    skillsHeader: "Skills",
    aboutHeader: "About Me",
    blogHeader: "My Blog",
    galleryHeader: "Photo Gallery",
    productsHeader: "My Products",
    orderBtn: "Order Now",
    orderModalTitle: "Order Placement",
    orderNameLabel: "Full Name",
    orderContactLabel: "Phone Number",
    orderCountryLabel: "Country",
    orderConfirmBtn: "Confirm Order",
    orderSuccess: "Thank you for placing your order. MD Ahbab Khan will contact you soon.",
    blogReadMore: "Read More",
    blogDesc: "Insights into my process and discoveries.",
    galleryDesc: "Visual snapshots of my creative journey.",
    contactHeader: "Get in Touch",
    contactSub: "Ready to start a new project? Let's talk.",
    contactEmailLabel: "Email Me",
    contactPhoneLabel: "Call Me",
    contactSocialLabel: "Social Networks",
    footerAdmin: "Admin Dashboard",
    loginHeader: "Security Access",
    loginIdLabel: "System ID",
    loginPassLabel: "Access Token",
    loginBtn: "Authorize",
    loginBack: "Exit to Portal",
    loginWelcome: "Welcome Admin",
    loginProceed: "Continue to Login",
    adminHeader: "System Core",
    adminSub: "Portfolio Management",
    adminMenu: "Control Center",
    adminBasic: "Core Identity",
    adminSkills: "Expertise",
    adminBlog: "Editorial",
    adminGallery: "Media Assets",
    adminNotice: "Global Broadcast",
    adminContact: "Contact Settings",
    adminDeploy: "Cloud Core",
    adminSave: "Sync Changes",
    adminSaving: "Syncing...",
    adminSaved: "Live!",
    adminLogout: "Disconnect",
    adminViewSite: "Public View",
    adminNewSkill: "Add Competency",
    adminNewPost: "Draft Story",
    adminNewPhoto: "Upload Media",
    adminNewLink: "Signal Link",
    adminTheme: "Visual Environment",
    adminVisibility: "Module Toggle",
    adminWorkplace: "Station",
    syncLoading: "Loading Profile...",
    visLabelAbout: "About Section",
    visLabelSkills: "Skills Section",
    visLabelBlog: "Blog Section",
    visLabelGallery: "Gallery Section",
    visLabelContact: "Contact Section",
    visLabelClock: "Live Clock",
    visLabelNotice: "Notice Board",
    visLabelWork: "Work Status",
    noticeLabel: "ALERT",
    noticePublished: "Broadcasted"
  },
  bn: {
    navAbout: "পরিচয়",
    navBlog: "ব্লগ",
    navGallery: "গ্যালারি",
    navContact: "যোগাযোগ",
    navAdmin: "অ্যাডমিন",
    heroWelcome: "আমার ডিজিটাল প্রোফাইলে স্বাগতম",
    heroIam: "আমি",
    heroEmailBtn: "পরিচয়",
    heroStatus: "অ্যাভেইলবল",
    heroWorkLabel: "বর্তমানে কর্মরত",
    clockLabel: "বাংলাদেশ সময়",
    skillsHeader: "দক্ষতাসমূহ",
    aboutHeader: "আমার সম্পর্কে",
    blogHeader: "ব্লগ",
    galleryHeader: "গ্যালারি",
    productsHeader: "পণ্যসমূহ",
    orderBtn: "অর্ডার করুন",
    orderModalTitle: "অর্ডার ফর্ম",
    orderNameLabel: "আপনার নাম",
    orderContactLabel: "ফোন নম্বর",
    orderCountryLabel: "দেশ",
    orderConfirmBtn: "অর্ডার সম্পন্ন করুন",
    orderSuccess: "অর্ডারটি সফলভাবে সম্পন্ন হয়েছে। শীঘ্রই আপনার সাথে যোগাযোগ করা হবে।",
    blogReadMore: "বিস্তারিত",
    blogDesc: "প্রযুক্তি এবং জীবনধারা নিয়ে আমার ভাবনা।",
    galleryDesc: "স্মৃতি এবং কাজের কিছু মুহূর্ত।",
    contactHeader: "যোগাযোগ করুন",
    contactSub: "আপনার কোনো আইডিয়া থাকলে সরাসরি কথা বলতে পারি।",
    contactEmailLabel: "ইমেইল করুন",
    contactPhoneLabel: "সরাসরি কল",
    contactSocialLabel: "সোশ্যাল মিডিয়া",
    footerAdmin: "ড্যাশবোর্ড",
    loginHeader: "সুরক্ষিত প্রবেশ",
    loginIdLabel: "ইউজার আইডি",
    loginPassLabel: "পাসওয়ার্ড",
    loginBtn: "লগইন",
    loginBack: "হোমে ফিরুন",
    loginWelcome: "স্বাগতম অ্যাডমিন",
    loginProceed: "লগইন করতে এগিয়ে যান",
    adminHeader: "সিস্টেম কন্ট্রোল",
    adminSub: "ম্যানেজমেন্ট ড্যাশবোর্ড",
    adminMenu: "কন্টেন্ট মেনু",
    adminBasic: "মৌলিক তথ্য",
    adminSkills: "দক্ষতাসমূহ",
    adminBlog: "ব্লগ ম্যানেজমেন্ট",
    adminGallery: "মিডিয়া ফাইল",
    adminNotice: "ব্রডকাস্ট",
    adminContact: "যোগাযোগ সেটিংস",
    adminSave: "লাইভ আপডেট",
    adminSaving: "আপডেট হচ্ছে...",
    adminSaved: "আপডেট হয়েছে!",
    adminLogout: "লগ আউট",
    adminViewSite: "ওয়েবসাইট ভিউ",
    adminNewSkill: "নতুন স্কিল",
    adminNewPost: "নতুন পোস্ট",
    adminNewPhoto: "ছবি যোগ করুন",
    adminNewLink: "নতুন লিংক",
    adminTheme: "ওয়েবসাইট থিম",
    adminVisibility: "সেকশন কন্ট্রোল",
    adminWorkplace: "কর্মস্থল",
    syncLoading: "ডাটা লোড হচ্ছে...",
    visLabelAbout: "সম্পর্কে সেকশন",
    visLabelSkills: "দক্ষতা সেকশন",
    visLabelBlog: "ব্লগ সেকশন",
    visLabelGallery: "গ্যালারি সেকশন",
    visLabelContact: "যোগাযোগ সেকশন",
    visLabelClock: "লাইভ ঘড়ি",
    visLabelNotice: "নোটিশ বোর্ড",
    visLabelWork: "কাজের স্ট্যাটাস",
    noticeLabel: "জরুরী নোটিশ",
    noticePublished: "প্রকাশিত"
  }
};
