
import { PortfolioData, OrderStatus } from './types';

export const CLOUD_SYNC_CONFIG = {
  BUCKET_ID: "ahbab_portfolio_v1_global",
  API_URL: "https://kvdb.io/An9rXmU8j8P7rPq8q8q8/data"
};

export const THEME_OPTIONS = [
  { id: 'neon', name: 'Cyber Azure', color: '#0ea5e9' },
  { id: 'gold', name: 'Luxury Gold', color: '#d4af37' },
  { id: 'rose', name: 'Deep Crimson', color: '#e11d48' },
  { id: 'emerald', name: 'Nordic Forest', color: '#10b981' }
];

export const ORDER_STATUS_OPTIONS: { id: OrderStatus; labelEn: string; labelBn: string; color: string }[] = [
  { id: 'pending', labelEn: 'Pending', labelBn: 'পেন্ডিং', color: '#f59e0b' },
  { id: 'processing', labelEn: 'Processing', labelBn: 'প্রসেসিং', color: '#3b82f6' },
  { id: 'shipped', labelEn: 'Shipped', labelBn: 'শিপড', color: '#8b5cf6' },
  { id: 'completed', labelEn: 'Completed', labelBn: 'সম্পন্ন', color: '#10b981' },
  { id: 'cancelled', labelEn: 'Cancelled', labelBn: 'বাতিল', color: '#ef4444' }
];

export const CURRENCY_SYMBOLS = ['৳', '$', '€', '£', '¥', '₹', 'د.إ'];

export const INITIAL_DATA: PortfolioData = {
  name: "John Doe",
  title: "Professional Web Developer",
  bio: "I am an experienced web developer and designer. I love learning new things and creating great digital solutions.",
  currentWork: "Frontend Engineer at Tech Corp",
  profileImage: "https://picsum.photos/400/400",
  aboutText: "Write details about yourself here. Discuss your work style, goals, and experience.",
  email: "example@mail.com",
  phone: "+880 1234 567 890",
  theme: 'neon',
  showAbout: true,
  showSkills: true,
  showBlog: true,
  showGallery: true,
  showContact: true,
  showClock: true,
  showNotice: true,
  showWork: true,
  showProducts: true,
  notice: {
    text: "Welcome to my updated portfolio! New projects coming soon.",
    updatedAt: new Date().toISOString()
  },
  socialLinks: [
    { id: "1", platform: "GitHub", url: "https://github.com" },
    { id: "2", platform: "LinkedIn", url: "https://linkedin.com" },
    { id: "3", platform: "Facebook", url: "https://facebook.com" }
  ],
  projects: [
    {
      id: "1",
      title: "Blog Post 1",
      description: "Write a summary of your first blog post here.",
      image: "https://picsum.photos/600/400?random=1",
      link: "#"
    }
  ],
  gallery: [
    { id: "1", image: "https://picsum.photos/800/800?random=10", title: "Moments" },
    { id: "2", image: "https://picsum.photos/800/800?random=11", title: "Travel" }
  ],
  skills: [
    { id: "1", name: "React" },
    { id: "2", name: "Tailwind CSS" }
  ],
  products: [
    { id: "1", name: "Premium Web Design", amount: "5000", currency: "৳", description: "Get a high-quality personal landing page for your brand.", image: "https://picsum.photos/600/600?random=20" }
  ],
  orders: []
};

export const TRANSLATIONS = {
  en: {
    navAbout: "About",
    navBlog: "Blog",
    navGallery: "Gallery",
    navContact: "Contact",
    navProducts: "Shop",
    navAdmin: "Admin",
    heroWelcome: "Welcome to my digital profile",
    heroIam: "I am",
    heroEmailBtn: "Send Email",
    heroStatus: "Available Now",
    heroWorkLabel: "Currently working at",
    clockLabel: "Bangladesh Time",
    skillsHeader: "Skills",
    aboutHeader: "About Me",
    blogHeader: "My Blog",
    galleryHeader: "Photo Gallery",
    productsHeader: "My Products",
    orderBtn: "Order Now",
    orderModalTitle: "Order Placement",
    orderNameLabel: "Full Name",
    orderContactLabel: "Phone Number",
    orderCountryLabel: "Country",
    orderConfirmBtn: "Confirm Order",
    orderSuccess: "Thank you for placing your order. One of our representatives will get in touch with you shortly to assist you further.",
    blogReadMore: "Read More",
    blogDesc: "Insights into my process and discoveries.",
    galleryDesc: "Visual snapshots of my creative journey.",
    contactHeader: "Get in Touch",
    contactSub: "Ready to start a new project? Let's talk.",
    contactEmailLabel: "Email Me",
    contactPhoneLabel: "Call Me",
    contactSocialLabel: "Social Networks",
    footerAdmin: "Admin Dashboard",
    loginHeader: "Security Access",
    loginSub: "Restricted Area",
    loginIdLabel: "System ID",
    loginPassLabel: "Access Token",
    loginBtn: "Authorize",
    loginBack: "Exit to Portal",
    adminHeader: "System Core",
    adminSub: "Portfolio Management",
    adminMenu: "Control Center",
    adminBasic: "Core Identity",
    adminSkills: "Expertise",
    adminBlog: "Editorial",
    adminGallery: "Media Assets",
    adminProducts: "Storefront",
    adminOrders: "Order Queue",
    adminNotice: "Global Broadcast",
    adminContact: "Access Points",
    adminDeploy: "Cloud Core",
    adminSave: "Sync Changes",
    adminSaving: "Syncing...",
    adminSaved: "Live!",
    adminLogout: "Disconnect",
    adminViewSite: "Public View",
    adminNewSkill: "Add Competency",
    adminNewPost: "Draft Story",
    adminNewPhoto: "Upload Media",
    adminNewProduct: "Stock Item",
    adminNewLink: "Signal Link",
    adminTheme: "Visual Environment",
    adminVisibility: "Module Toggle",
    adminWorkplace: "Station",
    adminOrderStatus: "Status",
    adminProductTitle: "Item",
    deployTitle: "Cloud Nexus",
    deployDesc: "Direct synchronization with the global database cluster.",
    deployStatus: "Node Status: Online",
    deploySyncId: "Bucket UID",
    deployCopy: "Copy Credentials",
    deployCopied: "Copied!",
    syncLoading: "Loading Profile...",
    syncError: "Neural link lost. Using cache.",
    visLabelAbout: "About Section",
    visLabelSkills: "Skills Section",
    visLabelBlog: "Blog Section",
    visLabelGallery: "Gallery Section",
    visLabelContact: "Contact Section",
    visLabelClock: "Live Clock",
    visLabelNotice: "Notice Board",
    visLabelWork: "Work Status",
    visLabelProducts: "Shop/Storefront",
    noticeLabel: "ALERT",
    noticePublished: "Broadcasted"
  },
  bn: {
    navAbout: "পরিচয়",
    navBlog: "ব্লগ",
    navGallery: "গ্যালারি",
    navContact: "যোগাযোগ",
    navProducts: "শপ",
    navAdmin: "অ্যাডমিন",
    heroWelcome: "আমার ডিজিটাল প্রোফাইলে স্বাগতম",
    heroIam: "আমি",
    heroEmailBtn: "পরিচয়",
    heroStatus: "অ্যাভেইলবল",
    heroWorkLabel: "বর্তমানে কর্মরত",
    clockLabel: "বাংলাদেশ সময়",
    skillsHeader: "দক্ষতাসমূহ",
    aboutHeader: "আমার সম্পর্কে",
    blogHeader: "মাই ব্লগ",
    galleryHeader: "ফটো গ্যালারি",
    productsHeader: "আমার পণ্যসমূহ",
    orderBtn: "অর্ডার করুন",
    orderModalTitle: "অর্ডার ফর্ম",
    orderNameLabel: "আপনার নাম",
    orderContactLabel: "ফোন নম্বর",
    orderCountryLabel: "দেশ",
    orderConfirmBtn: "অর্ডার সম্পন্ন করুন",
    orderSuccess: "আপনার অর্ডার দেওয়ার জন্য ধন্যবাদ। আমাদের একজন প্রতিনিধি শীঘ্রই আপনার সাথে যোগাযোগ করবেন এবং আপনাকে আরও সহায়তা করবেন।",
    blogReadMore: "বিস্তারিত",
    blogDesc: "প্রযুক্তি এবং জীবনধারা নিয়ে আমার ভাবনা।",
    galleryDesc: "স্মৃতি এবং কাজের কিছু মুহূর্ত।",
    contactHeader: "যোগাযোগ করুন",
    contactSub: "আপনার কোনো আইডিয়া থাকলে সরাসরি কথা বলতে পারি।",
    contactEmailLabel: "ইমেইল করুন",
    contactPhoneLabel: "সরাসরি কল",
    contactSocialLabel: "সোশ্যাল মিডিয়া",
    footerAdmin: "ড্যাশবোর্ড",
    loginHeader: "সুরক্ষিত প্রবেশ",
    loginSub: "অ্যাডমিন প্যানেল",
    loginIdLabel: "ইউজার আইডি",
    loginPassLabel: "পাসওয়ার্ড",
    loginBtn: "লগইন",
    loginBack: "হোমে ফিরুন",
    adminHeader: "সিস্টেম কন্ট্রোল",
    adminSub: "ম্যানেজমেন্ট ড্যাশবোর্ড",
    adminMenu: "কন্টেন্ট মেনু",
    adminBasic: "মৌলিক তথ্য",
    adminSkills: "দক্ষতাসমূহ",
    adminBlog: "ব্লগ ম্যানেজমেন্ট",
    adminGallery: "মিডিয়া ফাইল",
    adminProducts: "পণ্য তালিকা",
    adminOrders: "অর্ডার তালিকা",
    adminNotice: "ব্রডকাস্ট",
    adminContact: "যোগাযোগ",
    adminDeploy: "ক্লাউড স্টোরেজ",
    adminSave: "লাইভ আপডেট",
    adminSaving: "আপডেট হচ্ছে...",
    adminSaved: "আপডেট হয়েছে!",
    adminLogout: "লগ আউট",
    adminViewSite: "ওয়েবসাইট ভিউ",
    adminNewSkill: "নতুন স্কিল",
    adminNewPost: "নতুন পোস্ট",
    adminNewPhoto: "ছবি যোগ করুন",
    adminNewProduct: "নতুন পণ্য",
    adminNewLink: "নতুন লিংক",
    adminTheme: "ওয়েবসাইট থিম",
    adminVisibility: "সেকশন কন্ট্রোল",
    adminWorkplace: "কর্মস্থল",
    adminOrderStatus: "অবস্থা",
    adminProductTitle: "পণ্য",
    deployTitle: "ক্লাউড সিঙ্ক্রোনাইজেশন",
    deployDesc: "সরাসরি গ্লোবাল ডাটাবেসে সেভ হবে।",
    deployStatus: "সিঙ্ক স্ট্যাটাস: একটিভ",
    deploySyncId: "ইউনিক আইডি",
    deployCopy: "কপি আইডি",
    deployCopied: "কপি হয়েছে!",
    syncLoading: "ডাটা লোড হচ্ছে...",
    syncError: "সার্ভার কানেক্ট হতে পারেনি।",
    visLabelAbout: "সম্পর্কে সেকশন",
    visLabelSkills: "দক্ষতা সেকশন",
    visLabelBlog: "ব্লগ সেকশন",
    visLabelGallery: "গ্যালারি সেকশন",
    visLabelContact: "যোগাযোগ সেকশন",
    visLabelClock: "লাইভ ঘড়ি",
    visLabelNotice: "নোটিশ বোর্ড",
    visLabelWork: "কাজের স্ট্যাটাস",
    visLabelProducts: "শপ/স্টোর সেকশন",
    noticeLabel: "জরুরী নোটিশ",
    noticePublished: "প্রকাশিত"
  }
};

export const ADMIN_CREDENTIALS = {
  id: "Admin",
  password: "Ahbab85565"
};
